---
- name: Ensure paths exist
  ansible.builtin.file:
    path: "{{ item.directory }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: '0755'
  with_items: "{{ systemd_units }}"
  when: item.directory is defined

- name: Create the unit files
  ansible.builtin.template:
    src: "unit.j2"
    dest: "{{ item.directory | default('/etc/systemd/system/') }}/{{ item.name }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: '0644'
  with_items: "{{ systemd_units }}"
  notify: Reload systemd

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Configure the units
  ansible.builtin.systemd_service:
    name: "{{ item.name }}"
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(True) }}"
  with_items: "{{ systemd_units }}"
  when: item.managed is defined and item.managed
